export type EditorSymbol = { glyph: string; name: string; latex: string }
export type EditorSymbolCategory = { name: string; symbols: readonly EditorSymbol[] }

const symbol = (glyph: string, name: string, latex = glyph): EditorSymbol => ({ glyph, name, latex })

export const EDITOR_SYMBOL_CATEGORIES: readonly EditorSymbolCategory[] = [
  { name: 'Tez-tez', symbols: [symbol('π', 'Pi', '\\pi'), symbol('∞', 'Sonsuzluq', '\\infty'), symbol('±', 'Üstəgəl-mənfi', '\\pm'), symbol('≠', 'Bərabər deyil', '\\ne'), symbol('≈', 'Təxminən bərabər', '\\approx'), symbol('≤', 'Kiçik və ya bərabər', '\\le'), symbol('≥', 'Böyük və ya bərabər', '\\ge'), symbol('°', 'Dərəcə', '^{\\circ}')] },
  { name: 'Əməliyyatlar', symbols: [symbol('+', 'Toplama'), symbol('−', 'Çıxma', '-'), symbol('×', 'Vurma', '\\times'), symbol('÷', 'Bölmə', '\\div'), symbol('·', 'Vurma nöqtəsi', '\\cdot'), symbol('∓', 'Mənfi-üstəgəl', '\\mp')] },
  { name: 'Münasibətlər', symbols: [symbol('=', 'Bərabərdir'), symbol('<', 'Kiçikdir'), symbol('>', 'Böyükdür'), symbol('≡', 'Eynilik', '\\equiv'), symbol('∝', 'Mütənasibdir', '\\propto')] },
  { name: 'Çoxluqlar', symbols: [symbol('∈', 'Elementidir', '\\in'), symbol('∉', 'Elementi deyil', '\\notin'), symbol('∋', 'Özündə saxlayır', '\\ni'), symbol('⊂', 'Alt çoxluq', '\\subset'), symbol('⊆', 'Alt çoxluq və ya bərabər', '\\subseteq'), symbol('⊃', 'Üst çoxluq', '\\supset'), symbol('⊇', 'Üst çoxluq və ya bərabər', '\\supseteq'), symbol('∪', 'Birləşmə', '\\cup'), symbol('∩', 'Kəsişmə', '\\cap'), symbol('∅', 'Boş çoxluq', '\\emptyset')] },
  { name: 'Yunan hərfləri', symbols: [symbol('α', 'Alfa', '\\alpha'), symbol('β', 'Beta', '\\beta'), symbol('γ', 'Qamma', '\\gamma'), symbol('δ', 'Delta', '\\delta'), symbol('ε', 'Epsilon', '\\epsilon'), symbol('θ', 'Teta', '\\theta'), symbol('λ', 'Lambda', '\\lambda'), symbol('μ', 'Mü', '\\mu'), symbol('π', 'Pi', '\\pi'), symbol('ρ', 'Ro', '\\rho'), symbol('σ', 'Siqma', '\\sigma'), symbol('φ', 'Fi', '\\phi'), symbol('ω', 'Omeqa', '\\omega'), symbol('Γ', 'Böyük qamma', '\\Gamma'), symbol('Δ', 'Böyük delta', '\\Delta'), symbol('Θ', 'Böyük teta', '\\Theta'), symbol('Λ', 'Böyük lambda', '\\Lambda'), symbol('Σ', 'Böyük siqma', '\\Sigma'), symbol('Φ', 'Böyük fi', '\\Phi'), symbol('Ω', 'Böyük omeqa', '\\Omega')] },
  { name: 'Məntiq', symbols: [symbol('¬', 'İnkar', '\\neg'), symbol('∧', 'Və', '\\land'), symbol('∨', 'Və ya', '\\lor'), symbol('⇒', 'Nəticə', '\\Rightarrow'), symbol('⇔', 'Ekvivalent', '\\Leftrightarrow'), symbol('∀', 'Hər biri üçün', '\\forall'), symbol('∃', 'Mövcuddur', '\\exists'), symbol('∴', 'Deməli', '\\therefore'), symbol('∵', 'Çünki', '\\because')] },
  { name: 'Oxlar', symbols: [symbol('←', 'Sola ox', '\\leftarrow'), symbol('→', 'Sağa ox', '\\rightarrow'), symbol('↔', 'İkitərəfli ox', '\\leftrightarrow'), symbol('↑', 'Yuxarı ox', '\\uparrow'), symbol('↓', 'Aşağı ox', '\\downarrow'), symbol('⇐', 'Sola nəticə oxu', '\\Leftarrow')] },
  { name: 'Həndəsə', symbols: [symbol('∠', 'Bucaq', '\\angle'), symbol('∟', 'Düz bucaq', '\\rightangle'), symbol('⊥', 'Perpendikulyar', '\\perp'), symbol('∥', 'Paralel', '\\parallel'), symbol('△', 'Üçbucaq', '\\triangle'), symbol('□', 'Kvadrat', '\\square'), symbol('○', 'Dairə', '\\circ')] },
]
