"""add verification challenges

Revision ID: 0f3de393f0af
Revises: 92a8355b6004
Create Date: 2026-07-28 16:38:00.249240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3de393f0af'
down_revision: Union[str, Sequence[str], None] = '92a8355b6004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_challenges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'phone', name='verification_channel'), nullable=False),
    sa.Column('purpose', sa.Enum('verify_email', 'verify_phone', 'reset_password', 'change_email', 'change_phone', 'magic_login', 'multi_factor_authentication', name='verification_purpose'), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('send_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('failed_attempts >= 0', name='ck_verification_challenges_failed_attempts_non_negative'),
    sa.CheckConstraint('send_count >= 0', name='ck_verification_challenges_send_count_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_challenges_active_lookup', 'verification_challenges', ['user_id', 'purpose', 'channel'], unique=False, postgresql_where=sa.text('consumed_at IS NULL AND invalidated_at IS NULL'))
    op.create_index('ix_verification_challenges_destination_purpose_created_at', 'verification_challenges', ['destination', 'purpose', 'created_at'], unique=False)
    op.create_index('ix_verification_challenges_expires_at', 'verification_challenges', ['expires_at'], unique=False)
    op.create_index('ix_verification_challenges_user_purpose_created_at', 'verification_challenges', ['user_id', 'purpose', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_verification_challenges_user_purpose_created_at",
        table_name="verification_challenges",
    )
    op.drop_index(
        "ix_verification_challenges_expires_at",
        table_name="verification_challenges",
    )
    op.drop_index(
        "ix_verification_challenges_destination_purpose_created_at",
        table_name="verification_challenges",
    )
    op.drop_index(
        "ix_verification_challenges_active_lookup",
        table_name="verification_challenges",
        postgresql_where=sa.text(
            "consumed_at IS NULL AND invalidated_at IS NULL"
        ),
    )
    op.drop_table("verification_challenges")

    op.execute("DROP TYPE IF EXISTS verification_purpose")
    op.execute("DROP TYPE IF EXISTS verification_channel")
    # ### end Alembic commands ###