"""extend_user_relationships

Revision ID: 3a321e3c14e4
Revises: 5a19418816ef
Create Date: 2026-08-01 11:36:50.432671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a321e3c14e4'
down_revision: Union[str, Sequence[str], None] = '5a19418816ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_relationships', sa.Column('context_student_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_relationships_context_student_id'), 'user_relationships', ['context_student_id'], unique=False)
    op.create_foreign_key(None, 'user_relationships', 'users', ['context_student_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_relationships', type_='foreignkey')
    op.drop_index(op.f('ix_user_relationships_context_student_id'), table_name='user_relationships')
    op.drop_column('user_relationships', 'context_student_id')
    # ### end Alembic commands ###
