"""add_groups_grades_and_purposes

Revision ID: 59591a508874
Revises: b98663534e3a
Create Date: 2026-08-01 16:22:18.339541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59591a508874'
down_revision: Union[str, Sequence[str], None] = 'b98663534e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_name'), 'grades', ['name'], unique=True)
    op.create_table('purposes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purposes_name'), 'purposes', ['name'], unique=True)
    op.create_table('groups',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_teacher_id', sa.UUID(), nullable=False),
    sa.Column('member_category', sa.Enum('STUDENT', 'TEACHER', name='group_member_category', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_member_category'), 'groups', ['member_category'], unique=False)
    op.create_index(op.f('ix_groups_owner_teacher_id'), 'groups', ['owner_teacher_id'], unique=False)
    op.create_table('group_grades',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'grade_id', name='uq_group_grades_group_id_grade_id')
    )
    op.create_index(op.f('ix_group_grades_grade_id'), 'group_grades', ['grade_id'], unique=False)
    op.create_index(op.f('ix_group_grades_group_id'), 'group_grades', ['group_id'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('member_role', sa.Enum('OWNER', 'MEMBER', name='group_member_role', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'LEFT', 'REMOVED', name='group_membership_status', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_members_group_id_user_id')
    )
    op.create_index(op.f('ix_group_members_grade_id'), 'group_members', ['grade_id'], unique=False)
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_invited_by'), 'group_members', ['invited_by'], unique=False)
    op.create_index(op.f('ix_group_members_member_role'), 'group_members', ['member_role'], unique=False)
    op.create_index(op.f('ix_group_members_status'), 'group_members', ['status'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('group_purposes',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('purpose_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purpose_id'], ['purposes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'purpose_id', name='uq_group_purposes_group_id_purpose_id')
    )
    op.create_index(op.f('ix_group_purposes_group_id'), 'group_purposes', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_purposes_purpose_id'), 'group_purposes', ['purpose_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_purposes_purpose_id'), table_name='group_purposes')
    op.drop_index(op.f('ix_group_purposes_group_id'), table_name='group_purposes')
    op.drop_table('group_purposes')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_status'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_member_role'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_invited_by'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_grade_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_group_grades_group_id'), table_name='group_grades')
    op.drop_index(op.f('ix_group_grades_grade_id'), table_name='group_grades')
    op.drop_table('group_grades')
    op.drop_index(op.f('ix_groups_owner_teacher_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_member_category'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_purposes_name'), table_name='purposes')
    op.drop_table('purposes')
    op.drop_index(op.f('ix_grades_name'), table_name='grades')
    op.drop_table('grades')
    # ### end Alembic commands ###
