"""add_user_relationships

Revision ID: 5a19418816ef
Revises: bd4cba40f86a
Create Date: 2026-08-01 11:05:56.459096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a19418816ef'
down_revision: Union[str, Sequence[str], None] = 'bd4cba40f86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_relationships',
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('TEACHER_TO_STUDENT', 'TEACHER_TO_TEACHER', 'PARENT_TO_STUDENT', 'PARENT_TO_TEACHER', name='relationship_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'ENDED', 'BLOCKED', name='relationship_status', native_enum=False), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'recipient_id', 'relationship_type', name='uq_user_relationships_requester_recipient_type')
    )
    op.create_index(op.f('ix_user_relationships_recipient_id'), 'user_relationships', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_user_relationships_relationship_type'), 'user_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_user_relationships_requester_id'), 'user_relationships', ['requester_id'], unique=False)
    op.create_index(op.f('ix_user_relationships_status'), 'user_relationships', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_relationships_status'), table_name='user_relationships')
    op.drop_index(op.f('ix_user_relationships_requester_id'), table_name='user_relationships')
    op.drop_index(op.f('ix_user_relationships_relationship_type'), table_name='user_relationships')
    op.drop_index(op.f('ix_user_relationships_recipient_id'), table_name='user_relationships')
    op.drop_table('user_relationships')
    # ### end Alembic commands ###
