"""improve_relationship_constraints_and_blocking

Revision ID: b98663534e3a
Revises: 3a321e3c14e4
Create Date: 2026-08-01 12:00:10.150347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98663534e3a'
down_revision: Union[str, Sequence[str], None] = '3a321e3c14e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_relationships', sa.Column('blocked_by_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('uq_user_relationships_requester_recipient_type'), 'user_relationships', type_='unique')
    op.create_index(op.f('ix_user_relationships_blocked_by_id'), 'user_relationships', ['blocked_by_id'], unique=False)
    op.create_index('uq_user_relationships_with_context', 'user_relationships', ['requester_id', 'recipient_id', 'relationship_type', 'context_student_id'], unique=True, postgresql_where=sa.text('context_student_id IS NOT NULL'))
    op.create_index('uq_user_relationships_without_context', 'user_relationships', ['requester_id', 'recipient_id', 'relationship_type'], unique=True, postgresql_where=sa.text('context_student_id IS NULL'))
    op.create_foreign_key(None, 'user_relationships', 'users', ['blocked_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_relationships', type_='foreignkey')
    op.drop_index('uq_user_relationships_without_context', table_name='user_relationships', postgresql_where=sa.text('context_student_id IS NULL'))
    op.drop_index('uq_user_relationships_with_context', table_name='user_relationships', postgresql_where=sa.text('context_student_id IS NOT NULL'))
    op.drop_index(op.f('ix_user_relationships_blocked_by_id'), table_name='user_relationships')
    op.create_unique_constraint(op.f('uq_user_relationships_requester_recipient_type'), 'user_relationships', ['requester_id', 'recipient_id', 'relationship_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_relationships', 'blocked_by_id')
    # ### end Alembic commands ###
