"""add_purpose_hierarchy

Revision ID: bdfc885af5a5
Revises: 59591a508874
Create Date: 2026-08-01 17:05:09.209124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdfc885af5a5'
down_revision: Union[str, Sequence[str], None] = '59591a508874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purposes', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_purposes_parent_id'), 'purposes', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'purposes', 'purposes', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purposes', type_='foreignkey')
    op.drop_index(op.f('ix_purposes_parent_id'), table_name='purposes')
    op.drop_column('purposes', 'parent_id')
    # ### end Alembic commands ###
